scrape_configs:
  - job_name: "node-exporter"
    dns_sd_configs:
      - names:
          - 'tasks.monitoring_stack_node-exporter'
        type: 'A'
        port: 9100

    relabel_configs:
      - source_labels: [__meta_dns_name]
        regex: tasks\.monitoring_stack_node-exporter
        action: replace
        target_label: swarm_service
        replacement: node-exporter

      - source_labels: [__address__]
        target_label: instance

      - source_labels: [__address__]
        regex: 10\.0\.1\.5.*
        target_label: node
        replacement: manager

      - source_labels: [__address__]
        regex: 10\.0\.1\.16.*
        target_label: node
        replacement: prod1

      - source_labels: [__address__]
        regex: 10\.0\.1\.4.*
        target_label: node
        replacement: prod2
